''' 
    #https://github.com/taleinat/fuzzysearch
    This allows fuzzy search, for example find a motif with single mismatch.
    
    Alternatives recommended but I have not tried yet:
    https://github.com/Martinsos/edlib

'''
'''
    yigit@neb.com May 18, 20023
'''

# Example below.
# Need to write from file version otherwise need to escape line breaks..

from fuzzysearch import find_near_matches

sequence= '''\
CGAAATTAATACGACTCACTATAAGGCTTGCTTGTTCTTTTTGCAGAAGCTCAGAATAAAC
GCTCAACTTTGGCACCAAAACATGGGAGTGCACGAGTGCCCCGCGTGGCTGTGGCTGCTGC
TGAGCCTCCTGAGCCTCCCACTGGGACTGCCCGTGCTGGGGGCACCACCCAGACTGATCTG
CGACAGCCGGGTACTGGAGAGGTACCTGCTGGAAGCCAAAGAAGCCGAGAATATCACAACC
GGATGCGCCGAGCACTGCAGCCTCAACGAGAACATCACCGTACCGGACACAAAGGTCAACT
TCTACGCATGGAAGAGAATGGAAGTAGGACAGCAGGCCGTCGAAGTGTGGCAGGGGCTCGC
GCTGCTGAGCGAGGCGGTGCTGCGGGGCCAGGCCCTCCTCGTCAACAGCAGCCAGCCGTGG
GAGCCCCTCCAACTGCACGTCGACAAAGCGGTGAGCGGGCTCCGCAGCCTGACGACGCTGC
TGCGGGCCCTGGGCGCACAAAAGGAGGCCATCAGCCCGCCCGACGCGGCCAGCGCGGCACC
CCTCCGAACGATCACCGCGGACACGTTCAGGAAGCTGTTCAGAGTGTACAGCAACTTCCTC
CGCGGAAAGCTGAAACTGTACACCGGCGAAGCGTGCAGGACAGGGGACCGCTAGGACTGAC
TAGGATCTGGTTACCACTAAACCAGCCTCAAGAACACCCGAATGGAGTCTCTAAGCTACATA
ATACCAACTTACACTTTACAACATGTTGTCCCCCAAACTGTAGCCATTCGTATCTGCTCCTAATAA
AAAGAAAGTTTCTTCACATTCTAGCTAG'''

subsequence = 'AAAACAT' # distance = 1
x=find_near_matches(subsequence, sequence, max_l_dist=1)

print(x)
print("---")
print(x[0].start, x[0].matched)

#print(sequence[x[0].start:])
